create table if not exists public.owner_media_ingress_audit (
  id bigint generated by default as identity primary key,
  message_id text,
  chat_id text not null,
  source_type text not null,
  media_id text,
  media_mime_type text,
  media_filename text,
  media_caption text,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists owner_media_ingress_audit_message_id_key
  on public.owner_media_ingress_audit (message_id)
  where message_id is not null and message_id <> '';

create index if not exists owner_media_ingress_audit_chat_created_idx
  on public.owner_media_ingress_audit (chat_id, created_at desc);

create index if not exists owner_media_ingress_audit_created_idx
  on public.owner_media_ingress_audit (created_at desc);
